---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme: 'untitled'
production_url: 'http://www.gracecode.com'
base_path: '/'

posts:
  permalink: /posts/:filename.html
  summary_lines: 20
  latest: 12 

pages:
  #permalink: 'pretty'

