---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme: 'gracecode'
production_url: 'http://graceco.de'
base_path: '/wiki'

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
