---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme: 'untitled'
production_url: 'http://aggron'
base_path: '/'

posts:
  permalink: /posts/:filename/
  summary_lines: 20
  latest: 10

pages:
  #permalink: 'pretty'

