title: 無標題文檔
urls: http://static.gracecode.com
tagline: 
author:
    name: 明城
    email: lucky@gracecode.com
    github: feelinglucky
    twitter: feelinglucky
    feedburner: gracecode
server:
    file: http://files.gracecode.com
    lab: http://graceco.de
keywords: php,linux,javascript,android,gracecode,vim,tracker,blog,feelinglucky,明城,博客,生活,编程,代码,程序员
