---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '2.5'

'untitled':
    use: "theme"

production_url: 'http://www.gracecode.com'
base_path: '/'

_root:
  layout: page
  permalink: /:filename.html
  permalink_ext: true
  rss:
    enable: false
  paginator:
    enable: false

posts:
  layout: post
  date_format: "%Y-%m-%d"
  sort: ["date", "desc"]
  permalink: /posts/:filename.html
  permalink_ext: true
  summary_lines: 20
  latest: 12 
  rss:
    enable: false
  paginator:
    enable: true
    url: "/page/"
    per_page: 6
    root_page: '/'

projects:
  layout: page
  permalink: "/projects/:filename.html"
  permalink_ext: true
  rss:
    enable: false
  paginator:
    enable: false

manuals:
  layout: page
  permalink: "/:filename.html"
  permalink_ext: true
  rss:
    enable: false
  paginator:
    enable: false

"static":
    "use": 'static'

asset_pipeline:
  enable: false
